FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# lara-ore-address

This is a [lara-ore](https://github.com/railken/lara-ore) package

## Addresses Api [/addresses]

### List All Addresses [GET]

+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "addresses",
                    "id": "1",
                    "attributes": {
                        "name": "Prof. Quinten Toy",
                        "street": "791 Kuphal Manors Suite 140",
                        "zip_code": "47303",
                        "city": "D'Amoreland",
                        "province": "CT",
                        "country": "US",
                        "created_at": "2018-09-10 16:22:32",
                        "updated_at": "2018-09-10 16:22:32"
                    },
                    "links": {
                        "self": "http://polls.apiblueprint.org/api/admin/addresses/1"
                    }
                }
            ],
            "meta": {
                "pagination": {
                    "total": 1,
                    "count": 1,
                    "per_page": 10,
                    "current_page": 1,
                    "total_pages": 1
                }
            },
            "links": {
                "self": "http://polls.apiblueprint.org/api/admin/addresses?page=1",
                "first": "http://polls.apiblueprint.org/api/admin/addresses?page=1",
                "last": "http://polls.apiblueprint.org/api/admin/addresses?page=1"
            }
        }



### Create a New Address [POST]

+ Request (application/json)

        {
            "name": "Prof. Quinten Toy",
            "street": "791 Kuphal Manors Suite 140",
            "zip_code": "47303",
            "city": "D'Amoreland",
            "province": "CT",
            "country": "US"
        }


+ Response 201 (application/json)

    + Headers

            Location: /addresses/1

    + Body

            
            {
                "data": {
                    "type": "addresses",
                    "id": "1",
                    "attributes": {
                        "name": "Prof. Quinten Toy",
                        "street": "791 Kuphal Manors Suite 140",
                        "zip_code": "47303",
                        "city": "D'Amoreland",
                        "province": "CT",
                        "country": "US",
                        "created_at": "2018-09-10 16:22:32",
                        "updated_at": "2018-09-10 16:22:32"
                    },
                    "links": {
                        "self": "http://polls.apiblueprint.org/api/admin/addresses/2"
                    }
                }
            }